spring:
  # app이름
  application:
    name: mosi
  #DB연결정보
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: c##mosi
    password: mosi1234
  #ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

# 웹서버 포트
server:
  port: 9070

# 로그레벨
# trace > debug > info > warn > error > fatal
logging:
  level:
    root: info
