spring:
  # app 이름
  application:
    name: project

  # DB연결 정보
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: c##project
    password: project1234

  # Thymeleaf 템플릿 엔진 설정 (페이지 컨트롤러용)
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false  # 개발 시 캐시 비활성화 (변경사항 즉시 반영)
    encoding: UTF-8
    mode: HTML

  # 정적 리소스 설정
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0  # 개발 시 캐시 비활성화

  # MVC 설정
  mvc:
    static-path-pattern: /static/**

# 웹서버 포트
server:
  port: 9080

# 로그레벨
# trace > debug > info > warn > error > fatal
logging:
  level:
    com.kh.project: debug # 프로젝트 패키지는 디버그 레벨로 상세히 로깅
    org.springframework.jdbc: debug # JDBC 관련 로깅 디버그 레벨로 설정
    org.springframework.web: debug # 웹 관련 로깅 추가