spring:
  application:
    name: project
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: c##project
    password: project1234
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  servlet:
    session:
      timeout: 30m

server:
  port: 9080
  servlet:
    session:
      timeout: 1800
      tracking-mode: cookie
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        security: DEBUG
        web: DEBUG

juso:
  api:
    confmKey: "U01TX0FVVEgyMDI1MDcxMDE0MzMzNTExNTkzMTE="
    url: "https://business.juso.go.kr/addrlink/addrLinkApi.do"