spring:
  # app 이름
  application:
    name: project
  # DB연결 정보
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: c##project
    password: project1234
  #ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  
  # 세션 타임아웃 설정 (개발용)
  servlet:
    session:
      timeout: 30m  # 30분으로 설정

# 웹서버 포트
server:
  port: 9080
  #서버 세션 타임아웃 설정
  #기본은 1800(30분), 최소값 60(1분)
  servlet:
    session:
      timeout: 1800
      #클라이언트의 세션아이디를 서버가 받는 방식
      #1. 클라이언트의 쿠키정보를 읽어 요청할때마다 요청메세지 헤더에 세션아이디를 취득
      #2. 클라이언트의 쿼리스트링을 읽어 세션아이디를 취득
      tracking-mode: cookie
  # 에러 처리 설정
  error:
    whitelabel:
      enabled: false    # Spring Boot 기본 에러 페이지 비활성화
    include-message: always
    include-binding-errors: always

# 로그레벨
# trace > debug > info > warn > error > fatal
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG     #JDBCTemplate sql log
        security: DEBUG  #Spring Security debug log
        web: DEBUG      #Spring Web debug log
#    root: info

# 외부 API 키 설정
juso:
  api:
    confmKey: U01TX0FVVEgyMDI1MDcxMDE0MzMzNTExNTkzMTE=